server:
  port: 6666

spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    url: jdbc:mysql://localhost:3306/devdevil?useSSL=true&useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: devdevil
    password: devdevil666
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 5
  redis:
    host: localhost
    port: 6379

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true